version: "3.8"

services:
  database:
    container_name: mongodb-${MONGO_DATABASE}
    image: mongo:4.1-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    command: --auth

    ports:
      - 27017:27017

    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./mongo-volume:/data/db

  database-test:
    container_name: mongodb-${MONGO_DATABASE}-test
    image: mongo:4.1-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    command: --auth

    ports:
      - 27018:27017

    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./mongo-volume-test:/data/db
